"""add daily_weather table

Revision ID: 02256fc43ce9
Revises: 74882fd1dcf4
Create Date: 2026-08-25 19:24:12.523086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02256fc43ce9'
down_revision: Union[str, None] = '74882fd1dcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temp_max_f', sa.Float(), nullable=True),
    sa.Column('temp_min_f', sa.Float(), nullable=True),
    sa.Column('precipitation_in', sa.Float(), nullable=True),
    sa.Column('wind_speed_max_mph', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_weather_date'), 'daily_weather', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_weather_date'), table_name='daily_weather')
    op.drop_table('daily_weather')
    # ### end Alembic commands ###
