"""switch to garmin: athletes/activities schema changes

Revision ID: 74882fd1dcf4
Revises: bea91e23eee1
Create Date: 2026-08-25 19:02:12.374492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74882fd1dcf4'
down_revision: Union[str, None] = 'bea91e23eee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('source', sa.String(), nullable=False))
    op.add_column('activities', sa.Column('external_id', sa.BigInteger(), nullable=False))
    op.drop_index('ix_activities_strava_activity_id', table_name='activities')
    op.create_index(op.f('ix_activities_external_id'), 'activities', ['external_id'], unique=False)
    op.create_index(op.f('ix_activities_source'), 'activities', ['source'], unique=False)
    op.create_unique_constraint('uq_activities_source_external_id', 'activities', ['source', 'external_id'])
    op.drop_column('activities', 'strava_activity_id')
    op.add_column('athletes', sa.Column('garmin_email', sa.String(), nullable=False))
    op.add_column('athletes', sa.Column('display_name', sa.String(), nullable=True))
    op.drop_index('ix_athletes_strava_athlete_id', table_name='athletes')
    op.create_index(op.f('ix_athletes_garmin_email'), 'athletes', ['garmin_email'], unique=True)
    op.drop_column('athletes', 'access_token')
    op.drop_column('athletes', 'strava_athlete_id')
    op.drop_column('athletes', 'first_name')
    op.drop_column('athletes', 'refresh_token')
    op.drop_column('athletes', 'last_name')
    op.drop_column('athletes', 'token_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('athletes', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('athletes', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('athletes', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('athletes', sa.Column('strava_athlete_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('athletes', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_athletes_garmin_email'), table_name='athletes')
    op.create_index('ix_athletes_strava_athlete_id', 'athletes', ['strava_athlete_id'], unique=True)
    op.drop_column('athletes', 'display_name')
    op.drop_column('athletes', 'garmin_email')
    op.add_column('activities', sa.Column('strava_activity_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_activities_source_external_id', 'activities', type_='unique')
    op.drop_index(op.f('ix_activities_source'), table_name='activities')
    op.drop_index(op.f('ix_activities_external_id'), table_name='activities')
    op.create_index('ix_activities_strava_activity_id', 'activities', ['strava_activity_id'], unique=True)
    op.drop_column('activities', 'external_id')
    op.drop_column('activities', 'source')
    # ### end Alembic commands ###
